
apply plugin: "com.diffplug.spotless"

spotless {
    java {
        target '**/*.java'
        targetExclude("$buildDir/**/*.java")
        targetExclude('bin/**/*.java')
        googleJavaFormat().aosp()
        removeUnusedImports()
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }

    kotlin {
        target '**/*.kt'
        targetExclude("$buildDir/**/*.kt")
        targetExclude('bin/**/*.kt')
        ktlint().setEditorConfigPath("$project.rootDir/.editorconfig")
        suppressLintsFor {
            step = 'ktlint'
            shortCode = 'standard:function-naming'
        }
        trimTrailingWhitespace()
        leadingTabsToSpaces(4)
        endWithNewline()
    }

    kotlinGradle {
        target '*.gradle.kts' // default target for kotlinGradle
        ktlint() // or ktfmt() or prettier()
    }

    format 'misc', {
        target '**/*.gradle', '**/*.md', '**/.gitignore'
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }

    format 'xml', {
        target '**/*.xml'
        leadingTabsToSpaces(4)
        trimTrailingWhitespace()
        endWithNewline()
    }
}
